# Generated by Django 3.1 on 2020-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='Status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'In_Active')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='Subscription',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('notsubscribe', 'Not Subscribe to Any Package')], default='Not Subscribe to Any Package', max_length=100),
        ),
    ]
