# Generated by Django 3.1 on 2020-08-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20200819_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_single_video',
            old_name='Upload_Single_Video_id',
            new_name='Video_id',
        ),
    ]
