# Generated by Django 3.1 on 2020-08-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_delete_upload_single_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_Video',
            fields=[
                ('Single_Video_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title_Name', models.CharField(default='Title', max_length=100)),
                ('Difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('moderate', 'Moderate'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], default='', max_length=100)),
                ('Intensity', models.CharField(choices=[('level1', 'Level_1'), ('level2', 'Level_2'), ('level3', 'Level_3'), ('level4', 'Level_4')], default='', max_length=100)),
                ('Decsription', models.TextField(default='Desc')),
                ('Video', models.FileField(default='dummy.jpg', upload_to='Videos/')),
                ('Thumbnail', models.ImageField(default='dummy.jpg', upload_to='Thumbnail/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.category')),
                ('Trainer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.trainer_account')),
            ],
        ),
    ]
