# Generated by Django 3.1 on 2020-08-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_single_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Favorite_Video',
            fields=[
                ('Student_Favorite_Video_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.user_account')),
                ('Video_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.single_video')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Favorite_Teacher',
            fields=[
                ('Student_Favorite_Teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.user_account')),
                ('Teacher_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.trainer_account')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Favorite_Course',
            fields=[
                ('Student_Favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.course')),
                ('Student_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.user_account')),
            ],
        ),
    ]
