# Generated by Django 3.1 on 2020-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_student_favorite_course_student_favorite_teacher_student_favorite_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='Subscription',
        ),
        migrations.AddField(
            model_name='user_account',
            name='Subscription_Status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'In_Active')], default='inactive', max_length=100),
        ),
    ]
