# Generated by Django 3.1 on 2020-08-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_auto_20200824_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='Package_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.package'),
        ),
    ]
