# Generated by Django 3.1 on 2020-08-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_user_account_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='id',
        ),
        migrations.AddField(
            model_name='package',
            name='Package_subscription',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('notsubscribe', 'Not Subscribe to Any Package')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='Package_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
