# Generated by Django 3.1 on 2020-08-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_auto_20200824_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='Joining_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='Subscription_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
