# Generated by Django 3.1 on 2020-08-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_auto_20200824_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='Subscription_Date',
        ),
    ]
