# Generated by Django 3.1 on 2020-08-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_remove_user_account_subscription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_detail',
            name='Month',
        ),
        migrations.RemoveField(
            model_name='card_detail',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='card_detail',
            name='Year',
        ),
    ]
