# Generated by Django 3.1 on 2020-08-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_auto_20200824_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Package_Name',
        ),
    ]
