# Generated by Django 3.1 on 2020-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_card_detail_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='Amount',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
