# Generated by Django 3.1 on 2020-08-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0017_auto_20200826_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
