# Generated by Django 3.1 on 2020-08-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0018_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='Subject_Video_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.course'),
        ),
    ]
