# Generated by Django 3.1 on 2020-08-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_auto_20200826_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='Subject_Video_Id',
        ),
        migrations.AddField(
            model_name='course',
            name='Playlist_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.playlist'),
        ),
    ]
