# Generated by Django 3.1 on 2020-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0021_auto_20200826_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Status',
            field=models.CharField(choices=[('done', 'Done'), ('undone', 'Un_Done')], default='undone', max_length=100),
        ),
    ]
