# Generated by Django 3.1 on 2020-12-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_auto_20200827_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Trainer_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trainer_Id', to='superadmin.trainer_account'),
        ),
    ]
