# Generated by Django 3.1 on 2020-12-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0023_auto_20201214_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Trainer_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.trainer_account'),
        ),
    ]
